config/routes.rb
RailsLab3::Application.routes.draw do
  resources :notifications

  get "exchange/index"
  get "exchange/get_data"
  get "exchange/find"
  get "home/index"

  post 'exchange/index' => 'exchange#exchange_date'
  post 'exchange/index' => 'exchange#find'

   root 'home#index'

  

end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exchange_controller.rb
require 'net/http'
require 'uri'
require 'nokogiri'

class ExchangeController < ApplicationController
  def index
    if params[:xml_code]
      response = Net::HTTP.get(URI.parse("http://www.nbp.pl/kursy/xml/#{params[:xml_code]}.xml"))
    else
      response = Net::HTTP.get(URI.parse("http://www.nbp.pl/kursy/xml/LastC.xml"))
    end
    responseXML = Nokogiri::XML(response)

    @exchangeDate = responseXML.xpath('//tabela_kursow/data_publikacji').text

    @exchangeArray = responseXML.xpath('//tabela_kursow/pozycja').map do |i|
      {'nazwa_waluty' => i.xpath('nazwa_waluty').text,
       'kod_waluty' => i.xpath('kod_waluty').text,
       'kurs_kupna' => i.xpath('kurs_kupna').text,
       'kurs_sprzedazy' => i.xpath('kurs_sprzedazy').text}
    end

    if params[:search]
      if params[:search]["whole_word"] == '1'
        @exchangeArray = @exchangeArray.select{ |i| i["nazwa_waluty"] == params[:search]["text"] ||
            i["kod_waluty"] == params[:search]["text"]}
      else
        @exchangeArray = @exchangeArray.select{ |i| i["nazwa_waluty"].include?(params[:search]["text"]) ||
            i["kod_waluty"].include?(params[:search]["text"])}
      end

    end

    puts 'index'

  end

  def exchange_date
    xml_codes = Net::HTTP.get(URI.parse("http://www.nbp.pl/kursy/xml/dir.txt"))
    xml_codes_array = xml_codes.split(/\r\n/)
    date_str = params[:exchange_date]["date"]
    date = Date.strptime(date_str, "%d-%m-%Y").strftime("%y%m%d")

    xml_code = "lastC"

    xml_codes_array.each do |r|
      if r.include? date
        xml_code = r
        break
      end
    end

    redirect_to :action => "index", :xml_code => xml_code
  end

  def find
    puts 'OK'
  end
end

app/controllers/home_controller.rb
require 'server_updater'

class HomeController < ApplicationController
  def index
    ServerUpdater.new("aaa")
  end

  def self.test
    puts 'testaaa'
  end
end

app/controllers/notifications_controller.rb
require 'net/http'
require 'uri'
require 'nokogiri'

class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  def self.send_notifications
    response = Net::HTTP.get(URI.parse("http://www.nbp.pl/kursy/xml/LastC.xml"))
    exchangeDate = responseXML.xpath('//tabela_kursow/data_publikacji').text
    NoticeMailer.notice_email.deliver
  end

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render action: 'show', status: :created, location: @notification }
      else
        format.html { render action: 'new' }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchange_helper.rb
module ExchangeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/exchange/exchange_date.html.erb
<h1>Exchange#get_data</h1>
<p>Find me in app/views/exchange/get_data.html.erb</p>

app/views/exchange/find.html.erb
<h1>Exchange#find</h1>
<p>Find me in app/views/exchange/find.html.erb</p>

app/views/exchange/get_data.html.erb
<h1>Exchange#get_data</h1>
<p>Find me in app/views/exchange/get_data.html.erb</p>

app/views/exchange/index.html.erb
    <h3>Data publikacji: <%= @exchangeDate %></h3>

    <%= form_for :search, :method => 'get' do |f| %>
      Search for:
      <%= f.text_field :text, :value => params[:search] ? params[:search]['text'] : "" %>
      <%= f.submit "Find" %>
      <br/>
      whole word
      <%= f.check_box :whole_word, :checked => (params[:search] and params[:search]['whole_word'] == "1") ? true : false %>
      <br/>
    <% end %>

    <%= form_for :exchange_date do |f| %>
      <%= f.label "Date" %>
      <%= f.text_field :date, :class => "date-field", :value => Date.strptime(@exchangeDate).strftime("%d-%m-%Y") %>
      <%= f.submit "Change" %>
    <% end %>

    <table style="border:1px solid black;">
      <thead>
       <tr>
         <th>Nazwa waluty</th>
         <th>Kod waluty</th>
         <th>Kurs kupna</th>
         <th>Kurs sprzedazy</th>
       </tr>
      </thead>
      <tbody>
      <% @exchangeArray.each do |exchange| %>
      <tr>
        <td><%= exchange["nazwa_waluty"] %></td>
        <td><%= exchange["kod_waluty"] %></td>
        <td><%= exchange["kurs_kupna"] %></td>
        <td><%= exchange["kurs_sprzedazy"] %></td>
      </tr>
      <% end %>
      </tbody>
    </table>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsLab3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.9.1.js"></script>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

  <script type="text/javascript">
    $(document).ready(function() {
      $(function() {
          $( ".date-field" ).datepicker({dateFormat: 'dd-mm-yy', beforeShowDay: function(date) {
            var day = date.getDay();
              return [day == 1 || day == 2 || day == 3 || day == 4 || day == 5];
          }});
      });
    });
  </script>
</head>
<body>

<%= link_to "Show exchange rates", exchange_index_path() %>
<%= link_to "Notifications", notifications_path() %>

<%= yield %>

</body>
</html>

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.email %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @notification.email %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>